name: Django CI

on:
  push:
    branches: [ "Production" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.6]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |

        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install -r requirements.txt
        
    - name: Restart and Clear Cache
    
      run: |
        sudo systemctl restart apache2
        sudo systemctl reload apache2

